update troubleshooting and redirect to cics doc
IBM/cics-bundle-gradle pull request #113
Opened 2022-03-21 04:19 UTC by vera-chan

Signed-off-by: Vera <vera.xx.c@me.com>
Hi @tom-foyle , I created this PR to include Gradle log errors that need sysadmin's further help and provide links to CICS doc for further info. Could you review it? (I'll update the Maven README once the wording is finalized here)

2022-03-21 10:33 UTC, tom-foyle commented on README.md
> +Contact your system administrator to check the `messages.log` file of the CMCI JVM server. More information about how to resolve CMCI JVM server errors, see [Troubleshooting CMCI JVM server](https://
Looks like this is meant to say "**For** more information..."

2022-03-21 10:36 UTC, tom-foyle commented on README.md
> +The error occurs because the user ID that deploys the bundle doesn't have right access.
I would say "...doesn't have access to the bundles directory"

2022-03-21 10:38 UTC, tom-foyle requested changes
Couple of minor changes suggested but looks good otherwise :)

2022-03-21 12:41 UTC, vera-chan commented on README.md
> +Contact your system administrator to check the `messages.log` file of the CMCI JVM server. More information about how to resolve CMCI JVM server errors, see [Troubleshooting CMCI JVM server](https://
Fixed in the new commit

2022-03-21 12:41 UTC, vera-chan commented on README.md
> +The error occurs because the user ID that deploys the bundle doesn't have right access.
Fixed in the new commit

2022-03-22 11:11 UTC, tom-foyle approved these changes

2022-03-22 13:02 UTC, merged