Gradle 8 support
IBM/cics-bundle-gradle pull request #140
Opened 2023-10-25 22:31 UTC by stewartfrancis

- Adjusts API usage to remove some internal API usage that was deprecated in Gradle 7 and removed in Gradle 8.  There'll be more of this to do for Gradle 9, but I've not done that now.
- Updates tests to run on Gradle 7.6.1 and 8.3, derived from a commit from @ind1go
- Adds a new sample project which demonstrates how to build an OSGi bundle and repackage into a CICS bundle in the same module
- Adds a `cicsBundle` configuration which could be used to resolve the CICS bundle project by down-stream projects.  Does not add a `Component` so this could be easily published, but that would be a logical next
- Small rewrite of how the tasks are wired together to prevent eager task creation.

I did also notice that we had an unnecessary property on the package task, which I removed.  This technically breaks our API, so we may want to consider a major version bump (or just deprecating that property instead of removing it).  There are other things we might consider if doing a major version bump anyway, like the changes to how to register additional bundle part configuration that @KyeMaloy97 and I discussed (which I've now forgotten about entirely), and making the tasks usable independently of the project and extensions.

2023-11-01 11:14 UTC, ind1go requested changes

2023-11-01 11:14 UTC, ind1go commented on src/main/kotlin/com/ibm/cics/cbgp/DeployBundleTask.kt
> +
Do we need to decide on one place to have this modification? It's also in `BundlePlugin.kt`.

2023-11-01 11:14 UTC, ind1go commented on src/main/kotlin/com/ibm/cics/cbgp/PackageBundleTask.kt
> -
As discussed, can I suggest we make this PR compatible with the current version 1 train and release, then go to a v2 snapshot for removing this property and also the additional changes mentioned in the description.

2023-11-01 11:14 UTC, ind1go commented on src/test/groovy/com/ibm/cics/cbgp/GoldenPathTests.groovy
> +		gradleVersion << GradleVersions.GRADLE_VERSIONS
Seems fair. I was trying to find a way to test on all test versions without having to remember to add the where clause to every test when you make it.

Maybe (different PR) we can add an extension to Spock to check whether each spec's tests have `gradleVersion` as an input. I don't know if that's possible.

2023-11-01 11:14 UTC, ind1go commented on src/test/groovy/com/ibm/cics/cbgp/GradleVersions.groovy
> +    static List GRADLE_VERSIONS = ["7.6.1", "8.3"]
We state support for Gradle 5 in the README - should be testing there too.

2023-12-06 00:18 UTC, stewartfrancis commented
I've reintroduced the old property, and deprecated it.  Also addressed your other review comments (thanks) @ind1go ready for a re-review now.

2023-12-06 12:33 UTC, stewartfrancis commented on src/main/kotlin/com/ibm/cics/cbgp/DeployBundleTask.kt
> +
You're right, we shouldn't need it in the plugin and I'll remove

2023-12-06 12:34 UTC, stewartfrancis commented on src/main/kotlin/com/ibm/cics/cbgp/DeployBundleTask.kt
> +
Have updated now

2023-12-06 19:33 UTC, ind1go approved these changes

2023-12-06 19:33 UTC, merged